spring.application.name=Blogging
spring.datasource.url=jdbc:mysql://localhost:3306/bloging_db
spring.datasource.username=root
spring.datasource.password=Ankit@1232

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=secretKey123
jwt.expiration=86400000